export const FeaturedResults = [

  {
    "Name": "ONE POT CHICKEN & TOMATO RICE",
    "PricePerServing": "0.84",
    "CookTime": "35 Mins",
    "Servings": 4,
    "Img": "https://ui.assets-asda.com/dm/asdagroceries/284ab1c2-5aac-11ea-be74-e9168e0c2b9a_Hero?scl=1"
  },
  {
    "Name": "AUBERGINE RAMEN",
    "PricePerServing": "0.84",
    "CookTime": "95 Mins",
    "Servings": 4,
    "Img": "https://ui.assets-asda.com/dm/asdagroceries/433930a2-fec0-11ec-9911-bd14a47f13ec_Hero?scl=1"
  },
  {
    "Name": "CREAMY MISO MUSHROOM & SPINACH PIE",
    "PricePerServing": "0.84",
    "CookTime": "60 Mins",
    "Servings": 4,
    "Img": "https://ui.assets-asda.com/dm/asdagroceries/475e88df-fe96-11ec-9911-f347fd5c83c1_Square?scl=1"
  },
]

export const ListResults = [
  {

    Name: "ONE POT CHICKEN & TOMATO RICE",
    PricePerServing: "0.84",
    CookTime: "35 Mins",
    Servings: 4,
    Img: "https://ui.assets-asda.com/dm/asdagroceries/284ab1c2-5aac-11ea-be74-e9168e0c2b9a_Hero?scl=1",
    items: [
      { name: "Chicken thighs", freeWeigth: false },
      {
        name: "long grain white rice",
        freeWeigth: true,
      },
      { name: "Passata with garlic", freeWeigth: false },
      { name: "Frozen mixed vegetable", freeWeigth: false },
      { name: "Fresh coriander", freeWeigth: false },
      { name: "Onions", freeWeigth: true },
      { name: "Paprika", freeWeigth: true },
      { name: "chilli flakes", freeWeigth: true },
      { name: "Chicken stock cubes", freeWeigth: false },
      { name: "Black pepper", freeWeigth: true },
    ],
  },
  {
    Name: "AUBERGINE RAMEN",
    PricePerServing: "0.84",
    CookTime: "35 Mins",
    Servings: 4,
    Img: "https://ui.assets-asda.com/dm/asdagroceries/433930a2-fec0-11ec-9911-bd14a47f13ec_Hero?scl=1",
    items: [
      { name: "Chicken thighs", freeWeigth: false },
      {
        name: "long grain white rice",
        freeWeigth: true,
      },
      { name: "Passata with garlic", freeWeigth: false },
      { name: "Frozen mixed vegetable", freeWeigth: false },
      { name: "Fresh coriander", freeWeigth: false },
      { name: "Onions", freeWeigth: true },
      { name: "Paprika", freeWeigth: true },
      { name: "chilli flakes", freeWeigth: true },
      { name: "Chicken stock cubes", freeWeigth: false },
      { name: "Black pepper", freeWeigth: true },
    ],
  },
  {
    Name: "CREAMY MISO MUSHROOM & SPINACH PIE",
    PricePerServing: "0.84",
    CookTime: "35 Mins",
    Servings: 4,
    Img: "https://ui.assets-asda.com/dm/asdagroceries/475e88df-fe96-11ec-9911-f347fd5c83c1_Square?scl=1",
    items: [
      { name: "Chicken thighs", freeWeigth: false },
      {
        name: "long grain white rice",
        freeWeigth: true,
      },
      { name: "Passata with garlic", freeWeigth: false },
      { name: "Frozen mixed vegetable", freeWeigth: false },
      { name: "Fresh coriander", freeWeigth: false },
      { name: "Onions", freeWeigth: true },
      { name: "Paprika", freeWeigth: true },
      { name: "chilli flakes", freeWeigth: true },
      { name: "Chicken stock cubes", freeWeigth: false },
      { name: "Black pepper", freeWeigth: true },
    ],
  },
  {
    Name: "ONE POT CHICKEN & TOMATO RICE",
    PricePerServing: "0.84",
    CookTime: "35 Mins",
    Servings: 4,
    Img: "https://ui.assets-asda.com/dm/asdagroceries/433930a2-fec0-11ec-9911-bd14a47f13ec_Hero?scl=1",
    items: [
      { name: "Chicken thighs", freeWeigth: false },
      {
        name: "long grain white rice",
        freeWeigth: true,
      },
      { name: "Passata with garlic", freeWeigth: false },
      { name: "Frozen mixed vegetable", freeWeigth: false },
      { name: "Fresh coriander", freeWeigth: false },
      { name: "Onions", freeWeigth: true },
      { name: "Paprika", freeWeigth: true },
      { name: "chilli flakes", freeWeigth: true },
      { name: "Chicken stock cubes", freeWeigth: false },
      { name: "Black pepper", freeWeigth: true },
    ],
  },
  {
    Name: "AUBERGINE RAMEN",
    PricePerServing: "0.84",
    CookTime: "35 Mins",
    Servings: 4,
    Img: "https://ui.assets-asda.com/dm/asdagroceries/433930a2-fec0-11ec-9911-bd14a47f13ec_Hero?scl=1",
    items: [
      { name: "Chicken thighs", freeWeigth: false },
      {
        name: "long grain white rice",
        freeWeigth: true,
      },
      { name: "Passata with garlic", freeWeigth: false },
      { name: "Frozen mixed vegetable", freeWeigth: false },
      { name: "Fresh coriander", freeWeigth: false },
      { name: "Onions", freeWeigth: true },
      { name: "Paprika", freeWeigth: true },
      { name: "chilli flakes", freeWeigth: true },
      { name: "Chicken stock cubes", freeWeigth: false },
      { name: "Black pepper", freeWeigth: true },
    ],
  },
  {
    Name: "CREAMY MISO MUSHROOM & SPINACH PIE",
    PricePerServing: "0.84",
    CookTime: "35 Mins",
    Servings: 4,
    Img: "https://ui.assets-asda.com/dm/asdagroceries/475e88df-fe96-11ec-9911-f347fd5c83c1_Square?scl=1",
    items: [
      { name: "Chicken thighs", freeWeigth: false },
      {
        name: "long grain white rice",
        freeWeigth: true,
      },
      { name: "Passata with garlic", freeWeigth: false },
      { name: "Frozen mixed vegetable", freeWeigth: false },
      { name: "Fresh coriander", freeWeigth: false },
      { name: "Onions", freeWeigth: true },
      { name: "Paprika", freeWeigth: true },
      { name: "chilli flakes", freeWeigth: true },
      { name: "Chicken stock cubes", freeWeigth: false },
      { name: "Black pepper", freeWeigth: true },
    ],
  },
  {
    Name: "ONE POT CHICKEN & TOMATO RICE",
    PricePerServing: "0.84",
    CookTime: "35 Mins",
    Servings: 4,
    Img: "https://ui.assets-asda.com/dm/asdagroceries/433930a2-fec0-11ec-9911-bd14a47f13ec_Hero?scl=1",
    items: [
      { name: "Chicken thighs", freeWeigth: false },
      {
        name: "long grain white rice",
        freeWeigth: true,
      },
      { name: "Passata with garlic", freeWeigth: false },
      { name: "Frozen mixed vegetable", freeWeigth: false },
      { name: "Fresh coriander", freeWeigth: false },
      { name: "Onions", freeWeigth: true },
      { name: "Paprika", freeWeigth: true },
      { name: "chilli flakes", freeWeigth: true },
      { name: "Chicken stock cubes", freeWeigth: false },
      { name: "Black pepper", freeWeigth: true },
    ],
  },
  {
    Name: "ONE POT CHICKEN & TOMATO RICE",
    PricePerServing: "0.84",
    CookTime: "35 Mins",
    Servings: 4,
    Img: "https://ui.assets-asda.com/dm/asdagroceries/433930a2-fec0-11ec-9911-bd14a47f13ec_Hero?scl=1",
    items: [
      { name: "Chicken thighs", freeWeigth: false },
      {
        name: "long grain white rice",
        freeWeigth: true,
      },
      { name: "Passata with garlic", freeWeigth: false },
      { name: "Frozen mixed vegetable", freeWeigth: false },
      { name: "Fresh coriander", freeWeigth: false },
      { name: "Onions", freeWeigth: true },
      { name: "Paprika", freeWeigth: true },
      { name: "chilli flakes", freeWeigth: true },
      { name: "Chicken stock cubes", freeWeigth: false },
      { name: "Black pepper", freeWeigth: true },
    ],
  },
  {
    Name: "CREAMY MISO MUSHROOM & SPINACH PIE",
    PricePerServing: "0.84",
    CookTime: "35 Mins",
    Servings: 4,
    Img: "https://ui.assets-asda.com/dm/asdagroceries/475e88df-fe96-11ec-9911-f347fd5c83c1_Square?scl=1",
    items: [
      { name: "Chicken thighs", freeWeigth: false },
      {
        name: "long grain white rice",
        freeWeigth: true,
      },
      { name: "Passata with garlic", freeWeigth: false },
      { name: "Frozen mixed vegetable", freeWeigth: false },
      { name: "Fresh coriander", freeWeigth: false },
      { name: "Onions", freeWeigth: true },
      { name: "Paprika", freeWeigth: true },
      { name: "chilli flakes", freeWeigth: true },
      { name: "Chicken stock cubes", freeWeigth: false },
      { name: "Black pepper", freeWeigth: true },
    ],
  },
  {
    Name: "AUBERGINE RAMEN",
    PricePerServing: "0.84",
    CookTime: "35 Mins",
    Servings: 4,
    Img: "https://ui.assets-asda.com/dm/asdagroceries/433930a2-fec0-11ec-9911-bd14a47f13ec_Hero?scl=1",
    items: [
      { name: "Chicken thighs", freeWeigth: false },
      {
        name: "long grain white rice",
        freeWeigth: true,
      },
      { name: "Passata with garlic", freeWeigth: false },
      { name: "Frozen mixed vegetable", freeWeigth: false },
      { name: "Fresh coriander", freeWeigth: false },
      { name: "Onions", freeWeigth: true },
      { name: "Paprika", freeWeigth: true },
      { name: "chilli flakes", freeWeigth: true },
      { name: "Chicken stock cubes", freeWeigth: false },
      { name: "Black pepper", freeWeigth: true },
    ],
  },
  {
    Name: "ONE POT CHICKEN & TOMATO RICE",
    PricePerServing: "0.84",
    CookTime: "35 Mins",
    Servings: 4,
    Img: "https://ui.assets-asda.com/dm/asdagroceries/433930a2-fec0-11ec-9911-bd14a47f13ec_Hero?scl=1",
    items: [
      { name: "Chicken thighs", freeWeigth: false },
      {
        name: "long grain white rice",
        freeWeigth: true,
      },
      { name: "Passata with garlic", freeWeigth: false },
      { name: "Frozen mixed vegetable", freeWeigth: false },
      { name: "Fresh coriander", freeWeigth: false },
      { name: "Onions", freeWeigth: true },
      { name: "Paprika", freeWeigth: true },
      { name: "chilli flakes", freeWeigth: true },
      { name: "Chicken stock cubes", freeWeigth: false },
      { name: "Black pepper", freeWeigth: true },
    ],
  },
];

